# Generated by Django 5.2 on 2025-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned')], default='lost', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('contact_info', models.TextField()),
            ],
        ),
    ]
