# Generated by Django 5.2 on 2025-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_mobilereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilereport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_photos/'),
        ),
    ]
