# Generated by Django 5.2 on 2025-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_lostitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LostItem',
        ),
    ]
